{$IF CompilerVersion = 22}
  {$DEFINE DelphiXE}
{$ENDIF}

{$IF CompilerVersion = 23}
  {$DEFINE DelphiXE2}
{$ENDIF}

{$IF CompilerVersion = 24}
  {$DEFINE DelphiXE3}
{$ENDIF}

{$IF CompilerVersion = 25}
  {$DEFINE DelphiXE4}
{$ENDIF}

{$IF CompilerVersion = 26}
  {$DEFINE DelphiXE5}
{$ENDIF}

{$IF CompilerVersion = 27}
  {$DEFINE DelphiXE6}
{$ENDIF}

{$IF CompilerVersion = 28}
  {$DEFINE DelphiXE7}
{$ENDIF}

{$IF CompilerVersion = 29}
  {$DEFINE DelphiXE8}
{$ENDIF}

{$IF CompilerVersion >= 22}
  {$DEFINE DelphiXE_UP}
{$ENDIF}

{$IF CompilerVersion >= 23}
  {$DEFINE DelphiXE_UP}
  {$DEFINE DelphiXE2_UP}
{$ENDIF}

{$IF CompilerVersion >= 24}
  {$DEFINE DelphiXE_UP}
  {$DEFINE DelphiXE2_UP}
  {$DEFINE DelphiXE3_UP}
{$ENDIF}

{$IF CompilerVersion >= 25}
  {$DEFINE DelphiXE_UP}
  {$DEFINE DelphiXE2_UP}
  {$DEFINE DelphiXE3_UP}
  {$DEFINE DelphiXE4_UP}
{$ENDIF}

{$IF CompilerVersion >= 26}
  {$DEFINE DelphiXE_UP}
  {$DEFINE DelphiXE2_UP}
  {$DEFINE DelphiXE3_UP}
  {$DEFINE DelphiXE4_UP}
  {$DEFINE DelphiXE5_UP}
{$ENDIF}

{$IF CompilerVersion >= 27}
  {$DEFINE DelphiXE_UP}
  {$DEFINE DelphiXE2_UP}
  {$DEFINE DelphiXE3_UP}
  {$DEFINE DelphiXE4_UP}
  {$DEFINE DelphiXE5_UP}
  {$DEFINE DelphiXE6_UP}
{$ENDIF}

{$IF CompilerVersion >= 28}
  {$DEFINE DelphiXE_UP}
  {$DEFINE DelphiXE2_UP}
  {$DEFINE DelphiXE3_UP}
  {$DEFINE DelphiXE4_UP}
  {$DEFINE DelphiXE5_UP}
  {$DEFINE DelphiXE6_UP}
  {$DEFINE DelphiXE7_UP}
{$ENDIF}

{$IF CompilerVersion >= 29}
  {$DEFINE DelphiXE_UP}
  {$DEFINE DelphiXE2_UP}
  {$DEFINE DelphiXE3_UP}
  {$DEFINE DelphiXE4_UP}
  {$DEFINE DelphiXE5_UP}
  {$DEFINE DelphiXE6_UP}
  {$DEFINE DelphiXE7_UP}
  {$DEFINE DelphiXE8_UP}
{$ENDIF}

{$IF CompilerVersion >= 30}
  {$DEFINE DelphiXE_UP}
  {$DEFINE DelphiXE2_UP}
  {$DEFINE DelphiXE3_UP}
  {$DEFINE DelphiXE4_UP}
  {$DEFINE DelphiXE5_UP}
  {$DEFINE DelphiXE6_UP}
  {$DEFINE DelphiXE7_UP}
  {$DEFINE DelphiXE8_UP}
  {$DEFINE DelphiSeattle_UP}
{$ENDIF}

{$IF CompilerVersion >= 31}
  {$DEFINE DelphiXE_UP}
  {$DEFINE DelphiXE2_UP}
  {$DEFINE DelphiXE3_UP}
  {$DEFINE DelphiXE4_UP}
  {$DEFINE DelphiXE5_UP}
  {$DEFINE DelphiXE6_UP}
  {$DEFINE DelphiXE7_UP}
  {$DEFINE DelphiXE8_UP}
  {$DEFINE DelphiSeattle_UP}
  {$DEFINE DelphiBerlin_UP}
{$ENDIF}
